name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
          extra_fonts: ./fonts/*.ttf
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: sheaves.pdf
          path: main.pdf
      - name: move
        run: mkdir -p outputs; mv main.pdf outputs
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./outputs
          publish_branch: build
          force_orphan: true
        
